pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/chichocoria/proyecto_final_cf.git'
        BRANCH = 'testing' // Cambia esto si necesitas otra rama
        IMAGE_NAME = 'chichocoria/avatares-devops-api'
        DOCKERFILE_PATH = 'avatares-devops/api/Dockerfile'
        CONTEXT = 'avatares-devops/api'
        registryCredential = 'chichocoria-dockerhub'
        VERSION = "${BUILD_NUMBER}"
        SONARQUBE_CREDENTIALS = 'SonarQube-Token'
        SONARQUBE_URL = 'http://192.168.52.237:9000'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: "${BRANCH}", url: "${REPO_URL}"
            }
        }

        stage('SonarQube analysis') {
          def scannerHome = tool 'SonarScanner 4.0';
          withSonarQubeEnv('SonarQube') { // If you have configured more than one global server connection, you can specify its name
          sh "${scannerHome}/bin/sonar-scanner"
          }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def fullImageName = "${IMAGE_NAME}:${VERSION}"
                    docker.build(fullImageName, "-f ${DOCKERFILE_PATH} ${CONTEXT}")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    def fullImageName = "${IMAGE_NAME}:${VERSION}"
                    docker.withRegistry( '', registryCredential) {
                        docker.image(fullImageName).push()
                    }
                }
            }
        }
    }
}