pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/chichocoria/proyecto_final_cf.git'
        BRANCH = 'testing' // Cambia esto si necesitas otra rama
        IMAGE_NAME = 'chichocoria/avatares-devops-api'
        DOCKERFILE_PATH = 'avatares-devops/api/Dockerfile'
        CONTEXT = 'avatares-devops/api'
        registryCredential = 'chichocoria-dockerhub'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: "${BRANCH}", url: "${REPO_URL}"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}", "-f ${DOCKERFILE_PATH} ${CONTEXT}")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry( '', registryCredential) {
                        docker.image("${IMAGE_NAME}").push()
                    }
                }
            }
        }
    }
}