- name: Instalar MelalLB desde el Hosts para el Cluster RKE2 y habilitar Nginx controller como tipo LoadBalancer
  hosts: localhost
  tasks:
    - name: Test Reacheability
      ansible.builtin.ping:
    - name: Upgrade all apt packages
      apt:
        force_apt_get: yes
        upgrade: dist
      become: yes
    - name: Run Sccript named instalar-metallb-helm.sh
      become: yes
      ansible.builtin.script: ../../k8s/metallb/instalar-metallb-helm.sh