- name: install rke2 on master node
  hosts: master
  tasks:
  - name: Test Reacheability
    ansible.builtin.ping:
  - name: Upgrade all apt packages
    apt:
      force_apt_get: yes
      upgrade: dist
    become: yes
  - name: Ejecutar el instalador
    become: yes
    shell: curl -sfL https://get.rke2.io | sh -
  - name: Enable service
    become: yes
    shell: systemctl enable rke2-server.service
  - name: Start Service
    become: yes
    shell: systemctl start rke2-server.service